# Global settings
timezone: Asia/Shanghai

# Site settings
title: 学无止境的博客
email: weishishuo329@gmail.com
description: "好记性不如烂笔头"
baseurl: ""
url: "http://weishishuo.github.io"
#twitter_username: jekyllrb
github_username:  weishishuo

# Build settings
markdown: kramdown
# markdown: rdiscount
permalink: pretty
